Accounts
YukiY727/Twitter_clone pull request #3
Opened 2022-02-23 03:36 UTC by YukiY727

なんだかんだで復活することができたのですが、PRは別のものになってしまいました
申し訳ないです

2022-02-23 03:38 UTC, YukiY727 commented
[masayaさんのコメント](https://github.com/YukiY727/Twitter_clone/pull/1#pullrequestreview-882454171)

2022-02-23 03:46 UTC, YukiY727 commented
[AbstractBaseUserの実装](https://qiita.com/NOIZE/items/23a990c3a97d43443a12)
ですが、こちらはaccoutsのmodelに実装するのなのでしょうか？

2022-02-23 04:08 UTC, masaya09 commented
> [AbstractBaseUserの実装](https://qiita.com/NOIZE/items/23a990c3a97d43443a12) ですが、こちらはaccoutsのmodelに実装するのなのでしょうか？

その通りです。accounts/models.pyにAbstractBaseUserやBaseUserManagerを記述します。また、accounts/forms.pyにformを記述する必要があります。
そして、カスタムユーザーを作成する前にmigrateしていた場合、djangoのデフォルトユーザーがDBに反映されているので、DBを削除して、作成したカスタムユーザーモデルをmakemigrationsして、その後、DBに反映させるためにmigrateをする必要があります。


修正
scssファイルと.gitignoreファイルにエラーが出てるので最後1行空行をあけといてください。
templatesディレクトリ内にあるregistrationディレクトリの名称をaccountsに変更してください。

2022-02-24 11:05 UTC, YukiY727 commented
一応記事をみてUserは変えてみました。
また、testについてなのですが、python manage.py testだけではなく、なにかあたらしく書くものなのでしょうか？

2022-02-24 11:57 UTC, masaya09 commented
> 一応記事をみてUserは変えてみました。 また、testについてなのですが、python manage.py testだけではなく、なにかあたらしく書くものなのでしょうか？

testはアプリケーション作成時に自動的に作成されるtests.pyファイルに記述します。今回の場合、accounts/tests.pyに記述します。書き方に関しては[こちら](https://selfs-ryo.com/detail/django_test_1)や私のgitub上にあるtwittercloneappリポジトリを参考にしてみてください。

テストでは、
1. ユーザーが作成できているか
2. パスワードのバリデーションエラーの確認
3. メール作成時のバリデーションエラーは発生するか
などを確かめるテストを記述し、python manage.py testコマンドをでtestを実行し、テストが成功するかを確認します。

記事を参考にuserを作成していただいたと思いますが、urlや血液型に関するものも入れる必要があるかは考えた上で作成した方が良いです。カスタムユーザーにフィールドを作成すればするほど、それぞれのフィールドに関してテストする必要が出てきて大変になります。
カスタムユーザーで作成していただくとdjnagoの理解が深まって良いのですが、最初の頃はフィールドに入れるのはusername, email, is_active, is_staffなどの最低限だけでも大丈夫です。参考記事は公式ドキュメントよりも説明がわかりやすいので載せました。
実際の型は[公式ドキュメントの例](https://docs.djangoproject.com/ja/4.0/topics/auth/customizing/#a-full-example)の方が最初は良いかもしれません。

ただ実装されるのはyukiさんですので、どのように作成するかは任せます。

2022-02-25 04:24 UTC, masaya09 commented
訂正です。
os.path.joinを使用するように述べたと思いますが、Django3.1以降では、pathlibというものを使用する方がosをimportする必要もないし、また記述量が減って良いということがわかりましたので、os.path.joinで記載したところは以前のような書き方に戻していただいて大丈夫です。
以前cssが通らなかったのはos.path.joinを使用していなかったからではなく、templatesディレクトリの位置が悪かったからだと思います。
参考記事として[こちら](https://qiita.com/TomoyaT_qq/items/167d1105ddda0205d0ed)をあげておきます

2022-02-26 01:12 UTC, YukiY727 commented
```
   def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin
```
この部分をどのようなことをしているのでしょうか？

2022-02-26 01:42 UTC, masaya09 commented
> ```
>    def __str__(self):
>         return self.email
> 
>     def has_perm(self, perm, obj=None):
>         "Does the user have a specific permission?"
>         # Simplest possible answer: Yes, always
>         return True
> 
>     def has_module_perms(self, app_label):
>         "Does the user have permissions to view the app `app_label`?"
>         # Simplest possible answer: Yes, always
>         return True
> 
>     @property
>     def is_staff(self):
>         "Is the user a member of staff?"
>         # Simplest possible answer: All admins are staff
>         return self.is_admin
> ```
> 
> この部分をどのようなことをしているのでしょうか？

def __str__のところは、管理画面で表示されるものを決めています。ここでは、emailが表示されるようにしています。ユーザー名を表示させたいならば、return self.usernameとすれば良いです。

それ以下はパーミッションを独自で作成しています。パーミッションは簡単にいえばユーザーの権限をどの程度与えるかというものを定めるのですが、わざわざ作成しなくてもPermissionsMixinというものを継承すれば、パーミッション周りは自動でやってくれますので、以下のようにしていただければ大丈夫です。
```
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager, PermissionsMixin) # ここに追加

class MyUser(AbstractBaseUser, PermissionsMixin): #ここに追加
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    date_of_birth = models.DateField()
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['date_of_birth']

    def __str__(self):
        return self.email

def has_perm以下削除
```

2022-02-26 01:52 UTC, YukiY727 commented
丁寧に本当にありがとうございます。

2022-02-26 02:10 UTC, YukiY727 commented
masayaさんのtestをみさせてもらいました。

```
class SignUpTests(TestCase):
    def setUp(self):
        self.url = reverse('accounts:signup')

    def test_signup_get(self):
        response = self.client.get(self.url)
        view = resolve('/signup/')
        # ユーザーがURL/signup/のページをGETすれば、ステータスコードは200、すなわち’成功’となる。
        self.assertEquals(response.status_code, 200)
        # URL/signup/は正しいview関数(signup)を返す
        self.assertEquals(view.func, signup)

    def test_successful_signup_post(self):
        data = {
            'username': 'new_user',
            'password1': 'testpass1',
            'password2': 'testpass1',
        }
        post_response = self.client.post(self.url, data=data)
        mypostlist_url = reverse('tweet:mypostlist')
        # 'tweet:myposlist'にリダイレクトされることを確認
        self.assertRedirects(post_response, mypostlist_url)
        # Userオブジェクトが作成されていることを確認
        self.assertTrue(MyUser.objects.exists())
        # ユーザーが認証済みであることを確認
        get_response = self.client.get(mypostlist_url)
        user = get_response.context.get('user')
        self.assertTrue(user.is_authenticated)

    def test_invalid_signup_post(self):
        # 無効なフォームを送信すると、同じページ（'accounts:signup'）にリダイレクトする
        response = self.client.post(self.url, {})
        self.assertEquals(response.status_code, 200)
        # エラーメッセージがあることを確認
        form = response.context.get('form')
        self.assertTrue(form.errors)
        # Userオブジェクトが作成されていないことを確認
        self.assertFalse(MyUser.objects.exists())

    def test_with_different_passwords(self):
        response = self.client.post(self.url, {'username': 'new_user', 'password1': 'testpass2', 'password2': 'testpass3'})
        self.assertFormError(response, 'form', 'password2', '確認用パスワードが一致しません。')

    def test_with_short_passwords(self):
        response = self.client.post(self.url, {'username': 'new_user', 'password1': 'fghj39', 'password2': 'fghj39'})
        self.assertFormError(response, 'form', 'password2','このパスワードは短すぎます。最低 8 文字以上必要です。')

    def test_with_easily_passwords(self):
        response = self.client.post(self.url, {'username': 'new_user', 'password1': 'abcd1234', 'password2': 'abcd1234'})
        self.assertFormError(response, 'form', 'password2','このパスワードは一般的すぎます。')

    def test_with_existed_user(self):
        MyUser.objects.create_user('existing_user', '', 'testpass1')
        response = self.client.post(self.url, {'username': 'existing_user', 'password1': 'testpass1', 'password2': 'testpass1'})
        self.assertFormError(response, 'form', 'username','同じユーザー名が既に登録済みです。')
```
の
> ```self.assertEquals(view.func, signup)```

なのですが、viewをclass実装している場合、どのように書けばいいのでしょうか？
また、調べ方も知りたいです

2022-02-26 02:35 UTC, masaya09 commented
結論から述べると関数ベースでもクラスベースでもテストの記述方法は変わりません。

```
class SignUpTests(TestCase):
    def setUp(self):
        self.url = reverse('accounts:signup')

    def test_signup_get(self):
        response = self.client.get(self.url)
        view = resolve('/signup/')
        # ユーザーがURL/signup/のページをGETすれば、ステータスコードは200、すなわち’成功’となる。
        self.assertEquals(response.status_code, 200)
        # URL/signup/は正しいview関数(signup)を返す
        self.assertEquals(view.func, signup)
```
例えば、この部分はユーザー作成時のurlにきちんと飛べているのかを確かめるテストです。

```
def test_invalid_signup_post(self):
        # 無効なフォームを送信すると、同じページ（'accounts:signup'）にリダイレクトする
        response = self.client.post(self.url, {})
        self.assertEquals(response.status_code, 200)
        # エラーメッセージがあることを確認
        form = response.context.get('form')
        self.assertTrue(form.errors)
        # Userオブジェクトが作成されていないことを確認
        self.assertFalse(MyUser.objects.exists())

```
ここのテストは、ユーザー作成時に必要な事項がないときエラーが出され、かつユーザーが作成されていないことを確認しています。

yukiさんのviewから見ると、ユーザー作成が成功したらきちんとsuccess_urlに飛んでいるかや、self.request.POST['next'] == 'back':の時、きちんと指定したhtmlが表示されているのかを確かめるテストを記述したりします。

テストは、自分が想定した動きをしているのかを確認するためのものです。
例えば、本当はユーザー名がかぶると登録できないように設定したのに、テストをしたらそのようになっていない場合、自分のコードにエラーがあるということに気づけます。

2022-02-27 03:09 UTC, YukiY727 commented
testにそれっぽことを書いてみたのですが、  
>AttributeError: type object 'UserCreateView' has no attribute 'request'
と返ってきてしまい、どうしようもない状態です。なぜでしょう。

2022-02-27 04:08 UTC, masaya09 reviewed
現状、viewの実装が良くないのでテスト作成の前にviewの方を作成してください。
エラーの理由はそのままなのですが、UserCreateViewがrequestメソッドを持っていないからだというのがエラー原因です。

2022-02-27 04:08 UTC, masaya09 commented on ttter/accounts/views.py
> +            field.widget.attrs['class'] = 'form-control'
これはforms.pyファイルに記載してください。forms.pyファイルはurls.py同様に自作する必要があります。
~~また、def __init__のところは何のために作成しましたか？~~　→確認画面でフォームを保持するためだと理解しました。

modelで作成したfieldであるnicknameやdate-of-birthをfieldsに入れておきましょう。このままでは記入するためのformがないのでユーザー作成時に入力できません。特にnicknameはblankもnullもfalseで指定しているのでnicknameを入力しないとエラーが発生します。

2022-02-27 04:08 UTC, masaya09 commented on ttter/accounts/tests.py
> +        self.assertEquals(views.UserCreateView.request.POST['next'] == 'back', response)
assetEquals(a, b)はa==bであることを確かめます。self.request.POST['next'] == 'back'というのは条件であって、これがresponse、ここではreverse('accounts:create')と等しいということはならないので、テスト自体が異なります。

2022-02-27 04:08 UTC, masaya09 commented on ttter/accounts/views.py
> +        elif self.request.POST['next'] == 'regist':
正直ここの実装はあまり良いように思えません。というのも、html側の値で判断しているからです。この状態だとhtmlファイルを検証で書き換えられた時、思うような挙動が起きない可能性が高いです。~~ユーザー登録した後にユーザーを確認する欄を作りたい場合はforms.pyでUserConfirmFormなどを作成して、それを返すように設定してください。~~

訂正
views.pyにそれぞれユーザー情報を入れるviewと入力したものを確認するためのviewをそれぞれ作成してください。[こちら](https://blog.narito.ninja/detail/45/)が参考になります。

2022-03-01 02:01 UTC, YukiY727 commented
誕生日をいれる枠をしたの記事のような形で表示させたいのですが、記事はformsを使っており、いま私が使っているUserCretionFormsではどのようにすればいいのかがわかりません。教えていただけると助かります。
(inputs_forms)[https://qiita.com/peijipe/items/009fc487505dfdb03a8d]

2022-03-01 02:02 UTC, YukiY727 commented
そっれぽいtestを書いてみたのですが、よくわからないエラー文が出てしまし、調べてもよくわかりません。
<img width="1475" alt="スクリーンショット 2022-03-01 110121" src="https://user-images.githubusercontent.com/83635663/156090647-c8330ae9-aa21-40ea-9367-77ffa60b6158.png">
> raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'base.urls' from 'C:\\Users\\tsube\\OneDrive\\デスクト  プ\\back\\twitter_clone2\\ttter\\base\\urls.py'> (bas
ップ\\back\\twitter_clone2\\ttter\\base\\urls.py'> (base:base) ''>, <URLPattern '' [name='top']>], [<URLResolver <module 'accounts.urls' from 'C:\\Users\\tsube\\OneDrive\\デスクトッ counts:accounts) 'accounts/'>]], 'path': 'create_data_e:base) ''>, <URLPattern '' [name='top']>], [<URLResolv
プ\\back\\twitter_clone2\\ttter\\accounts\\urls.py'> (accounts:accounts) 'accounts/'>]], 'path': 'create_data_input/'}

2022-03-01 02:28 UTC, masaya09 commented
誕生日表示のところに関しては、以下のように記載すれば良いと思います。

```
accounts/forms.py

class SignUpForm(UserCreationForm)
    date_of_birth = forms.DateTimeField(
        label='誕生日',
        required=True,
        widget=forms.DateInput(attrs={"type": "date"}),
        input_formats=['%Y-%m-%d']
    )

    class Meta: 
     　  以下同じ
```
    
```

2022-03-01 02:58 UTC, masaya09 commented
テストに関して、UserDataInputは関数ではなくクラスですので、テストの記述が間違っています。

getで予定したhtmlファイルを表示できているならそれでいいです。すなわち

```
accounts/tests.py

def test_signup_get(self):
        response = self.client.get(self.url)
        view = resolve('/create_data_input/') # いらない
        self.assertEquals(response.status_code, 200) #ここで、予定したurlに行けてるのでok
        self.assertEquals(view.func, UserDataInput) # いらない
```

テストとしては他に、
データをきちんと入力したらそこで登録されずにconfirmのページにいくのかのテスト
データに不備がある場合エラーが発生するのかのテスト
1. 名前が不適
2. passwordが不適
3. メールの記載が不適
4. ニックネームを記載していない
など、どの時にエラーが発生するのか、そしてそのエラーがきちんと表示されているのかを確認するテストを作成
confirmのページから登録したらユーザーがデータに登録できているかを確認するテスト

以上のようなテストを実施してください。

2022-03-02 04:11 UTC, masaya09 commented
> 
> > `self.assertEquals(view.func, signup)`
> 
> なのですが、viewをclass実装している場合、どのように書けばいいのでしょうか？ また、調べ方も知りたいです

ここの質問見逃していました、すみません！
そのせいでこんがらせてしまいましたよね、申し訳ないです。

2022-05-27 08:40 UTC, YukiY727 commented
少しtestを変えてみたのですが、
```
FAIL: test_successful_signup_post (accounts.tests.SignUpTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tsube\OneDrive\デスクトップ\back\twitter_clone2\ttter\accounts\tests.py", line 26, in test_successful_signup_post
    self.assertRedirects(post_response, mypostlist_url, status_code=302, target_status_code=200)
  File "C:\Users\tsube\OneDrive\デスクトップ\back\twitter_clone2\venv\lib\site-packages\django\test\testcases.py", line 351, in assertRedirects
    self.assertEqual(
AssertionError: 200 != 302 : Response didn't redirect as expected: Response code was 200 (expected 302)
```
と出てしまい、本来302が変えるはずなのに200がかえってしまいます。どのように対処しればいいのでしょうか？

2022-05-27 09:51 UTC, masaya09 commented on ttter/accounts/forms.py
> +from .models import MyUser
```suggestion
MyUser = get_user_model()
```
で統一しましょう。
`from .models  import MyUser`でもMyUserモデルは取ってこれるのですが、get_user_model()で取ってくる方向でいきましょう。

2022-05-27 09:51 UTC, masaya09 commented on ttter/accounts/tests.py
> +        self.assertRedirects(post_response, mypostlist_url)
ここはそもそもリダイレクトされていません。
```
self.assertEquals(post_response.status_code, 200)
```
でUserDataInputのViewテストは確かめられています。
redirectするのは、UserDataCreateのViewにおいてです。

UserDataInputのViewでは、accounts/data_input.htmlにrenderしているので
`self.assertTemplateUsed(response, 'accounts/data_input.html')`
で、accounts/data_input.htmlが使用されているかをテストします。

UserDataConfirmのViewテストでは、同様に
```
self.assertEquals(post_response.status_code, 200)
```
の形でテストしていただければ大丈夫です。ここも同様に、self.assertTemplateUsedで指定したhtmlファイルが使われているかを確かめてください。また、難易度高めなので、実装するかしないかは任せますが、forms.pyで指定した
```
def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].widget.render_value = True
        self.fields['password2'].widget.render_value = True
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
```
部分から、UserDataInputのViewで記載したデータがUserDataConfirmのViewに保持されているかを確かめてみてください。
UserDataCreateのViewではUserが作成されているか、topにredirectできているかを確かめてください。

以上のように各ビューで作成した機能がきちんとなされているかをテストでは確かめていきます。

2022-05-27 09:51 UTC, masaya09 commented on ttter/accounts/urls.py
> +    path('create_user/', views.UserDataCreate.as_view(), name='create_user'),
```suggestion
    path('user_data_input/', views.UserDataInput.as_view(), name="user_data_input"),
    path('user_data_confirm/', views.UserDataConfirm.as_view(), name="user_data_confirm"),
    path('user_data_create/', views.UserDataCreate.as_view(), name='user_data_create'),
```
このようにview名と一致させておいた方がわかりやすいですね。とはいえ直すかどうかはお任せします。

2022-05-27 09:51 UTC, masaya09 commented on ttter/accounts/tests.py
> +        }
emailが必須になっているので、emailデータも入れてください。nicknameとdate_of_birthもforms.pyでフィールドに入れてるのでこれらのデータも入れておいた方がいいですね。

2022-05-27 09:51 UTC, masaya09 commented on ttter/accounts/views.py
> +                      {'form': form})
form_valid関数も追加してください。基本的に、ここではバリデーション後のcleaned_dataをauthenticateメソッドに入れてからsuccess_urlにリダイレクトさせてください。

2022-06-03 02:45 UTC, YukiY727 commented
一旦修正できるところは修正したので確認お願いします！

あと、
>また、難易度高めなので、実装するかしないかは任せますが、forms.pyで指定した

>def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].widget.render_value = True
        self.fields['password2'].widget.render_value = True
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

>部分から、UserDataInputのViewで記載したデータがUserDataConfirmのViewに保持されているかを確かめてみてください。
UserDataCreateのViewではUserが作成されているか、topにredirectできているかを確かめてください。

>以上のように各ビューで作成した機能がきちんとなされているかをテストでは確かめていきます。

の部分がどのように実装すればいいか見当がつかない状態なのでヒントもらえるとありがたいです。

2022-06-03 09:10 UTC, masaya09 commented on ttter/accounts/tests.py
> +
```suggestion
self.assertContains(response, 'new_user')
```
例えば、このようにassertContainsを使用することでuser_data_confirmのviewにpostした際のcreate.htmlには'new_user'のテキストが含まれていることが確認できます。

2022-06-03 09:10 UTC, masaya09 commented on ttter/accounts/views.py
> +        return redirect(self.success_url)
```
from django.contrib.auth import authenticate, login

def form_valid(self, form):
    form.save()
    email = form.cleaned_data.get('email')
    password = form.cleaned_data.get('password1')
    user = authenticate(email=email, password=password)
    if user is not None:
        login(self.request, user)
        return super().form_valid(form)
```
[こちら](https://docs.djangoproject.com/ja/4.0/topics/auth/default/#how-to-log-a-user-in)を参考に上のように作成します。
form_valid関数は[こちら](https://docs.djangoproject.com/ja/4.0/ref/class-based-views/mixins-editing/#django.views.generic.edit.FormMixin.form_valid)にあるようにデフォルトで設定したsuccess_urlにリダイレクトします。ですので、ここをそのままsuperメソッドを用いて継承させます。

authenticateメソッドの内容は[こちら](https://docs.djangoproject.com/ja/4.0/topics/auth/default/#authenticating-users)から確認してください。ここに書かれているようにauthenticateメソッドは認証バックエンドに対して問い合わせ、認証バックエンドで認証情報が有効とされれば Userオブジェクトを返します。認証バックエンドについては[こちら](https://docs.djangoproject.com/ja/4.0/topics/auth/customizing/#authentication-backends)で確認してください。
form.cleaned_dataに関しては[こちら](https://docs.djangoproject.com/ja/4.0/topics/forms/#field-data)にあるようにformで検証後のデータが格納されたものとなります。

2022-06-10 02:03 UTC, YukiY727 commented
```
if form.is_valid():
```
という記述をよく見かけるのですが、
```
def from_valid(self, form):
```
とは何が違うのでしょう？

2022-06-10 02:23 UTC, YukiY727 commented
```
AssertionError: 200 != 302 : Response didn't redirect as expected: Response code was 200 (expected 302)
```
testで上のようになってしまい、redirectがうまくいってないみたいなのですが、原因が全然わかりません、、、

2022-06-10 02:37 UTC, masaya09 commented
結論から言うと
if form.is_valid()はvalidがtrueかfalseを判断するもの。
def from_valid(self, form):は汎用ビューのメソッドでsuccess_urlにリダイレクトするものです。

以下説明
def form_validはdjangoの汎用ビューの中にあるメソッドです。このメソッドはis_validがtrueになった時に呼び出されるメソッドですので、if form.is_validはすでに実施された段階です。通常の状態ではform_validメソッドが呼び出されると、success_urlにリダイレクトするという処理が行われるのですが、そこをオーバーライドしてただ単にsuccess_urlにリダイレクトさせず、ユーザー作成した段階でログインさせる処理を行なっています。

ログイン処理時にauthenticateを使うので、ここで記載してもらいました。authenticate()によりメールとパスワードの認証が行われ、login()によりランダムに生成されたセッションIDをキーにしてログイン情報をセッションに保存させています。

2022-06-10 02:42 UTC, masaya09 commented on ttter/accounts/tests.py
> +        self.assertRedirects(response, base_url)
user_data_confirmは
```
 def form_valid(self, form):
        return render(self.request, 'accounts/create_confirm.html',
                      {'form': form})
```
となっています。これより、user_data_confirmの段階ではリダイレクトされていません。
リダイレクトされるのは、user_data_createの段階です。

2022-06-10 06:15 UTC, YukiY727 commented
細かく説明してくださり、ありがとうございます

2022-06-10 06:19 UTC, YukiY727 commented
test_data_createを作ってみたのですが、なぜだかUserオブジェクトがないよと怒られてしまいます。
よく考えてみると

2022-06-10 09:18 UTC, YukiY727 commented on ttter/accounts/tests.py
> +        self.assertTemplateUsed(confirm_response, 'accounts/create.html')
testのエラーで
```
Traceback (most recent call last):
  File "C:\Users\tsube\OneDrive\デスクトップ\back\twitter_clone2\ttter\accounts\tests.py", line 69, in test_data_create
    self.assertTrue(User.objects.exists())
AssertionError: False is not true
```
と出てしまい、そもそもこの部分でcreate.htmlに飛んでるのが変だなーというどうなってるのかさっぱりです、、、

2022-06-10 09:49 UTC, masaya09 commented on ttter/accounts/tests.py
> +        self.assertTemplateUsed(confirm_response, 'accounts/create.html')
> そもそもこの部分でcreate.htmlに飛んでいるのが変
UserDataConfirmのviewのform_validメソッドより、入力したフォームが正しければ、accounts/create_confirm.htmlに飛ぶようになっています。
しかし、今回はaccounts/create.htmlとしており、ここでテストが成功している　→　form_invalidメソッドの方が実行されている。つまり、入力したデータがバリデーションエラーを起こしていると言うことです。


error_message = confirm_response.context.get('form')
print(error_message.errors)
などでエラーが出るので確認してみてください。

おそらくですが、
```
'email': 'newuser@mail.com',
'date_of_birth': '2000-01-01',
```
emailとdate_of_birthは上のような形式で書かなければいけないというものかもしれませんね。

2022-06-10 15:54 UTC, masaya09 reviewed
成功テストはできているので、エラーのテストも書いてみてください。

2022-06-10 15:54 UTC, masaya09 commented on ttter/accounts/tests.py
> +        self.assertContains(confirm_response, 'testpass1')
ここ同じなので、１つだけでいいです

2022-06-10 15:54 UTC, masaya09 commented on ttter/accounts/tests.py
> +        }
このdataはtest_data_createの方でも使っているので、setUpにまとめてしまってください。

2022-06-10 15:54 UTC, masaya09 commented on ttter/accounts/tests.py
> +        self.url = reverse('accounts:user_data_confirm')
UserDataConfirmTestsとSignUpTestsは統合しちゃいましょう。その上で、url系とdataはsetUpにまとめてしまってください。かなりスッキリすると思います。

2022-06-12 11:12 UTC, YukiY727 commented on ttter/accounts/tests.py
> +        print(error_message.errors)
outputが
```
Found 11 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
...
........
----------------------------------------------------------------------
Ran 11 tests in 0.230s

OK
```
このようになってしまい、printがうまく出ないのですが、原因がわかりません。

2022-06-12 11:51 UTC, masaya09 commented on ttter/accounts/tests.py
> +        print(error_message.errors)
そもそもフォームエラーが起きてないので出力されていないだけですね。
```
User.objects.create_user(username="newuser", email="newuser@mail.com", password="testpass1")
```
から直接ユーザー作成して試してみてください。

ちなみにエラーが起きていないのは、`self.url_confirm = reverse('accounts:user_data_confirm')`にpostしてもユーザーはまだ作成されていないためです。

2022-06-14 03:51 UTC, YukiY727 commented on ttter/accounts/tests.py
> +        print(error_message.errors)
なるほど、ありがとうございます

2022-06-14 04:29 UTC, masaya09 reviewed
テストよく書けていると思います！
実装も良いと思うのであとは細かいところだけ調整お願いします

2022-06-14 04:29 UTC, masaya09 commented on ttter/accounts/tests.py
> +            self.url_confirm, data=empty_data)
user_data_confirmのビューでエラーが出たら、accounts/create.htmlへとrenderするようになってると思うので、assertTemplateUsedを用いて確認してみてください。

2022-06-14 04:29 UTC, masaya09 commented on ttter/accounts/tests.py
> +    def test_duplicate_user(self):
```suggestion
    def test_duplicate_username_and_email(self):
```
とした方がいいかもです

2022-06-14 04:29 UTC, masaya09 commented on ttter/.gitignore
> +*.sqlite3
最後に空行つけてください。また、.gitignoreファイルは複数あってもいいですが、もしまとめられそうな部分があったらまとめて対応してください。

2022-06-17 00:34 UTC, masaya09 approved these changes
LGTM

2022-06-18 06:00 UTC, Akinori13 requested changes
いくつかコメントしました！いい感じです！！！！
- requirements.txtを追加して、用いたライブラリを書いてください
- アカウント登録周りを再検証してください。

2022-06-18 06:00 UTC, Akinori13 commented on ttter/base/views.py
> +        return ctx
ここは意味がありますか

2022-06-18 06:00 UTC, Akinori13 commented on ttter/accounts/tests.py
> +    def test_short_password(self):
一番下のtest_short_passwordとは何が違いますか。関数名が被っていませんか？

2022-06-18 06:00 UTC, Akinori13 commented on ttter/static/css/style.scss
> +        position: absolute;
自分の環境だとフォームの要素がクリックできないですが、どうでしょうか？
yukiさんの環境で問題なければ修正しなくてよいです

2022-06-18 06:00 UTC, Akinori13 commented on ttter/accounts/views.py
> +    戻る場合は、POSTで飛んできたフォームデータをそのままuser_data_input.htmlに渡します。
何かの記事をコピーしたのだと思いますが、2点注意が必要です
- コピペが法律上の問題に発生する可能性があります。参考にするのは良いですが注意を払ってください。一度GitHubにデータを送信するとGitHub社に処理を依頼しなければ完全な削除ができません。間違って機密情報が漏洩することの内容に注意を払わなければなりません。
- 「user_data_input.htmlに渡します」とはこのクラスの処理として適切な内容ですか？

2022-06-20 01:55 UTC, YukiY727 commented on ttter/base/views.py
> +        return ctx
むかしのコードが残ってしまっていたみたいです。しゅうせいします。

2022-06-20 01:58 UTC, YukiY727 commented on ttter/accounts/tests.py
> +    def test_short_password(self):
修正しました。

2022-06-20 03:49 UTC, YukiY727 commented on ttter/accounts/views.py
> +    戻る場合は、POSTで飛んできたフォームデータをそのままuser_data_input.htmlに渡します。
コピーの件了解しました。
最初、何から始めればいいかわからず、記事の内容をそのまま貼り付けてしまいました。すいません
docsの内容に関してはtemplate名を変えたので、適切な内容ではないです。削除しました。

2022-06-20 07:53 UTC, YukiY727 commented on ttter/static/css/style.scss
> +        position: absolute;
自分のほうでも入力できない状態なっていたので、cssを変更したのですが、runserverしたときに修正した内容が反映されないのですが、なぜなんでしょう？

2022-06-22 04:53 UTC, Akinori13 commented on ttter/static/css/style.scss
> +        position: absolute;
pythonファイルを変更した場合のみ自動アップデートされるのが原因だと思います

2022-06-22 04:57 UTC, Akinori13 requested changes
よいです。以下の対応をお願いします。
- 使ってないモジュールのimport文を削除
- requirements.txtの追加の対応

2022-06-22 04:57 UTC, Akinori13 commented on ttter/accounts/tests.py
> +        print(error_message.errors)
削除

2022-06-22 04:57 UTC, Akinori13 commented on ttter/static/css/style.scss
> +        position: absolute;
反映確認しました

2022-06-22 05:49 UTC, YukiY727 commented on ttter/static/css/style.scss
> +        position: absolute;
そうなんですね
ありがとうございます

2022-06-22 05:55 UTC, YukiY727 commented on ttter/accounts/tests.py
> +        print(error_message.errors)
了解です

2022-06-22 06:34 UTC, Akinori13 commented
LGTM

2022-06-22 06:38 UTC, merged