login,logout実装、testうまくいかない
YukiY727/Twitter_clone pull request #4
Opened 2022-07-04 04:07 UTC by YukiY727

2022-07-07 14:37 UTC, masaya09 reviewed
requirements.txtにblack, flake8, isortを記入してください。インストール漏れがないように記述したら、仮想環境内でpip install -r requirements.txtをお願いします。

2022-07-07 14:37 UTC, masaya09 commented on .vscode/settings.json
> +  }
ファイル保存すれば自動的に最後空行が加わるはずなのでファイル保存お願いします。

2022-07-07 14:37 UTC, masaya09 commented on ttter/accounts/views.py
> +from django.views.generic import CreateView, FormView, TemplateView
使用していないモジュールは削除してください。flake8によりerrorが表示されているはずです。

2022-07-07 14:37 UTC, masaya09 commented on ttter/templates/accounts/login.html
> +{% endblock %}
ここも最後空行

2022-07-07 14:37 UTC, masaya09 commented on ttter/accounts/tests.py
> +        self.assertRedirects(response_post, reverse("base:top"))
redirect先は、base:topなのですが、settings.LOGIN_REDIRECT_URLから値が取れるので、settings.LOGIN_REDIRECT_URLに変更してください。

2022-07-07 14:37 UTC, masaya09 commented on ttter/accounts/tests.py
> +            reverse("base:top"),
ここも同様に、settings.LOGOUT_REDIRECT_URLに変更してください。

2022-07-07 14:37 UTC, masaya09 commented on ttter/accounts/tests.py
> +    def test_success_post(self):
追加で、ユーザーがログイン状態にあるかを確かめてください。確認方法はsession_keyを持っているかどうかで確認できます。

2022-07-07 14:37 UTC, masaya09 commented on ttter/accounts/tests.py
> +    def test_success_logout(self):
ここも同様に、ユーザーがログアウト状態にあるかを確認してください。先の逆、つまりsession_keyを持っていないことを確かめてみてください。

2022-07-07 14:37 UTC, masaya09 commented on ttter/accounts/forms.py
> +        fields = ("email", "username", "nickname", "date_of_birth")
date_of_birthに関して、カレンダーから日付指定できるようにしていたと記憶していますが、それを消した理由はありますか？今の状態だと適切なdatefieldの書き方を書くのは難しいので、せめてhelp_textかplaceholderを付与して、書き方を提示した方が良いでしょう。

2022-07-07 14:37 UTC, masaya09 commented on ttter/accounts/views.py
>      def from_valid(self, form):
```suggestion
    def form_valid(self, form):
```
これ前回のレビュー漏れかもですが、form_validです。これに僕も気づかず延々とユーザー作成時にログイン状態にならなくてどうしてだろうと路頭に迷ってました笑

2022-07-07 14:37 UTC, masaya09 commented on ttter/accounts/tests.py
> +            "password2": "abcdefgh",
このパスワードではユーザー登録できていないと思います。

2022-07-08 01:52 UTC, YukiY727 commented on ttter/accounts/views.py
>      def from_valid(self, form):
自分のほうだと問題なくいってたの謎ですね

2022-07-08 02:05 UTC, masaya09 commented on ttter/accounts/views.py
>      def from_valid(self, form):
いえ、うまく行ってないと思いますよ。もしうまく行っているなら、signupした後home画面にlogoutが表示されるはずです（signupしてもloginとsignupの文字があるはず）。from_validの状態でもユーザー自体は作成されますがログイン状態にはなっていなかったはずです。

テストでの確認方法として、ユーザー作成成功のtest（self.assertTrue(User.objects.exists()の下）に
`self.assertIn(SESSION_KEY, self.client.session)`を追記してみてください。from_validのままだと失敗するはずです。

2022-07-08 02:15 UTC, YukiY727 commented on ttter/accounts/forms.py
> +        fields = ("email", "username", "nickname", "date_of_birth")
もともと作っていませんでした
カレンダー難しそうなので、ダイヤル？みたいな感じで表示するように修正しました

2022-07-08 02:23 UTC, masaya09 approved these changes
LGTM

2022-07-09 01:51 UTC, Akinori13 requested changes
かなりいいと思います！テストについて少しコメントしたので、対応をお願いします！

2022-07-09 01:51 UTC, Akinori13 commented on ttter/accounts/tests.py
> +        self.url = reverse("accounts:login")
`"accounts:login"`ではなくsettings.LOGIN_URLを用いましょう

2022-07-09 01:51 UTC, Akinori13 commented on ttter/accounts/tests.py
> +        self.url = reverse("accounts:login")
他も同様にハードコーディングしないようにしてください

2022-07-09 01:51 UTC, Akinori13 commented on ttter/accounts/tests.py
> +        self.client.post(reverse("accounts:user_data_create"), data)
ここではサインアップ機能のテストと切り離したいので、create_userしてloginさせるようにしてください

2022-07-09 01:51 UTC, Akinori13 commented on ttter/accounts/tests.py
> +            reverse(settings.LOGOUT_REDIRECT_URL),
good

2022-07-09 01:53 UTC, YukiY727 commented on ttter/accounts/tests.py
> +        self.url = reverse("accounts:login")
承知です！

2022-07-09 01:57 UTC, YukiY727 commented on ttter/accounts/tests.py
> +        self.client.post(reverse("accounts:user_data_create"), data)
なるほど、切り離すのですね
了解です！

2022-07-09 02:38 UTC, Akinori13 commented on ttter/accounts/tests.py
> +        )
client.login()でログインさせてください

2022-07-09 03:50 UTC, Akinori13 commented on ttter/accounts/tests.py
> +        )
今の状態だと、ログアウトする前でログインできていません。ユーザーをログインさせましょう

`client.login()`は以下のように用います。
```
self.client.login(username="testuser", password="test_password")
```
force_loginでもいいでしょう。
```
user = User.objects.create_user(
            username="test", email="test@ed.jp", password="t12e12s12t"
        )
        self.client.force_login(user)
```

2022-07-09 03:51 UTC, YukiY727 commented on ttter/accounts/tests.py
> +        )
すいません、ありがとうございます

2022-07-09 04:01 UTC, merged